<i title="Cash" class="cacsh"></i>
<i title="MasterCard" class="mastercard"></i>
<i title="Visa" class="visa"></i>
<i title="WebMoney" class="webmoney"></i>
<i title="Qiwi" class="qiwi"></i>
<i title="Sberbank" class="sbrf"></i>
<i title="Alfa" class="alfa"></i>
<i title="Mir" class="mir"></i>
<i title="Jcb" class="jcb"></i>
<i title="PayPal" class="paypal"></i>
<i title="Maestro" class="maestro"></i>
<i title="Yoomoney" class="yoomoney"></i>
<i title="Yookassa" class="yookassa"></i>
<i title="Belkart" class="belkart"></i>
<i title="Halva" class="halva"></i>
<i title="Tinkoff" class="tinkoff"></i>